FROM ubuntu:18.04

RUN apt-get update 
RUN apt-get install -y software-properties-common 
RUN add-apt-repository ppa:deadsnakes/ppa 
#RUN add-apt-repository -y "deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main" 
RUN apt-get install -yq python3.6 python3-pip htop nano git wget 
RUN apt-get install -yq libglib2.0-0 autoconf automake 
RUN apt-get install -yq libtool build-essential unzip 
RUN apt-get install -yq libarchive-dev vim
RUN apt-get install -yq curl unzip

# Install Python dependencies.
ADD requirements.txt /
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

RUN pip install "widgetsnbextension==3.5.1"
RUN pip install jupyter-contrib-core jupyter-contrib-nbextensions jupyter-nbextensions-configurator

# Install Jupyter.
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension
RUN jupyter contrib nbextension install
RUN jupyter nbextension enable codefolding/main
RUN echo "c.NotebookApp.ip = '*'" >> /root/.jupyter/jupyter_notebook_config.py
RUN echo "c.NotebookApp.port = 8080" >> /root/.jupyter/jupyter_notebook_config.py
#RUN echo "c.NotebookApp.token = ''" >> /root/.jupyter/jupyter_notebook_config.py
RUN echo "jupyter notebook --no-browser --allow-root" >> /usr/local/bin/run_notebook && chmod +x /usr/local/bin/run_notebook

###
# AWS CLI
###

RUN cd /tmp \
	&& curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
        && unzip awscliv2.zip \
        && ./aws/install

# Welcome message.
ADD docker_cpu/welcome_message.txt /
RUN echo '[ ! -z "$TERM" -a -r /etc/motd ] && cat /etc/motd' \
        >> /etc/bash.bashrc \
        ; cat welcome_message.txt > /etc/motd

WORKDIR /root
EXPOSE 8080

#expose port 22 for remote vscode
EXPOSE 22 
